"""Add PostgreSQL archive runtime storage.

Revision ID: 20260612_0005
Revises: 20260610_0004
Create Date: 2026-06-12
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "20260612_0005"
down_revision: str | None = "20260610_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _execute(sql: str) -> None:
    op.execute(sql)


TENANT_TABLES = (
    ("archive", "detections"),
    ("archive", "probes"),
    ("archive", "runtime_state"),
)


def upgrade() -> None:
    _execute("CREATE SCHEMA IF NOT EXISTS archive AUTHORIZATION eva_owner")
    _execute("REVOKE ALL ON SCHEMA archive FROM PUBLIC")
    _execute("SET LOCAL ROLE eva_owner")
    _execute(
        """
        CREATE TABLE archive.detections (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id uuid NOT NULL,
            dedupe_key text NOT NULL,
            event_timestamp_ms bigint NOT NULL CHECK (event_timestamp_ms >= 0),
            recorded_at_ms bigint NOT NULL CHECK (recorded_at_ms >= 0),
            probe_id text NOT NULL,
            probe_name text,
            channel_id bigint NOT NULL CHECK (channel_id > 0),
            severity text,
            bookmark_enabled boolean NOT NULL DEFAULT false,
            bookmark_sent boolean NOT NULL DEFAULT false,
            pos_score double precision,
            neg_score double precision,
            margin double precision,
            thumbnail_b64 text,
            source text NOT NULL DEFAULT 'probe',
            payload_json jsonb,
            shard_key text NOT NULL,
            image_path text,
            clip_vec bytea,
            dino_vec bytea,
            dino_ready boolean NOT NULL DEFAULT false,
            created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            UNIQUE (tenant_id, id),
            UNIQUE (tenant_id, dedupe_key),
            CHECK (dedupe_key = btrim(dedupe_key) AND dedupe_key <> ''),
            CHECK (probe_id = btrim(probe_id) AND probe_id <> ''),
            CHECK (source = btrim(source) AND source <> ''),
            CHECK (shard_key = btrim(shard_key) AND shard_key <> ''),
            CHECK (
                payload_json IS NULL
                OR jsonb_typeof(payload_json) IN ('object', 'array')
            )
        )
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_detections_probe_ts
        ON archive.detections (tenant_id, probe_id, event_timestamp_ms DESC)
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_detections_channel_ts
        ON archive.detections (tenant_id, channel_id, event_timestamp_ms DESC)
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_detections_source_ts
        ON archive.detections (tenant_id, source, event_timestamp_ms DESC)
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_detections_source_channel_ts
        ON archive.detections (tenant_id, source, channel_id, event_timestamp_ms DESC)
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_detections_recorded
        ON archive.detections (tenant_id, recorded_at_ms DESC)
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_detections_shard_ts
        ON archive.detections (tenant_id, shard_key, event_timestamp_ms DESC)
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_detections_shard_id
        ON archive.detections (tenant_id, shard_key, id)
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_detections_dino_ready
        ON archive.detections (tenant_id, dino_ready, id DESC)
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_detections_image_path
        ON archive.detections (tenant_id, image_path)
        WHERE image_path IS NOT NULL
        """
    )

    _execute(
        """
        CREATE TABLE archive.probes (
            tenant_id uuid NOT NULL,
            probe_id text NOT NULL,
            payload_json jsonb NOT NULL CHECK (jsonb_typeof(payload_json) = 'object'),
            created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            PRIMARY KEY (tenant_id, probe_id),
            CHECK (probe_id = btrim(probe_id) AND probe_id <> '')
        )
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_probes_updated
        ON archive.probes (tenant_id, updated_at DESC)
        """
    )

    _execute(
        """
        CREATE TABLE archive.runtime_state (
            tenant_id uuid NOT NULL,
            state_key text NOT NULL,
            payload_json jsonb NOT NULL CHECK (jsonb_typeof(payload_json) = 'object'),
            created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            PRIMARY KEY (tenant_id, state_key),
            CHECK (state_key = lower(btrim(state_key)) AND state_key <> ''),
            CHECK (length(state_key) <= 128)
        )
        """
    )

    for schema, table in TENANT_TABLES:
        qualified = f"{schema}.{table}"
        policy = f"{schema}_{table}_tenant_isolation"
        _execute(f"ALTER TABLE {qualified} ENABLE ROW LEVEL SECURITY")
        _execute(f"ALTER TABLE {qualified} FORCE ROW LEVEL SECURITY")
        _execute(
            f"""
            CREATE POLICY {policy} ON {qualified}
            USING (
                tenant_id = NULLIF(current_setting('eva.tenant_id', true), '')::uuid
            )
            WITH CHECK (
                tenant_id = NULLIF(current_setting('eva.tenant_id', true), '')::uuid
            )
            """
        )

    _execute(
        "GRANT USAGE ON SCHEMA archive "
        "TO eva_api, eva_worker, eva_agent_reader, eva_backup"
    )
    _execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA archive "
        "TO eva_api, eva_worker"
    )
    _execute(
        "GRANT SELECT ON archive.detections, archive.probes "
        "TO eva_agent_reader"
    )
    _execute("GRANT SELECT ON ALL TABLES IN SCHEMA archive TO eva_backup")
    _execute(
        "GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA archive "
        "TO eva_api, eva_worker"
    )
    _execute("GRANT SELECT ON ALL SEQUENCES IN SCHEMA archive TO eva_backup")
    _execute("RESET ROLE")


def downgrade() -> None:
    _execute("SET LOCAL ROLE eva_owner")
    _execute("DROP SCHEMA IF EXISTS archive CASCADE")
    _execute("RESET ROLE")
