"""Add durable operator feedback for archived VLM alerts.

Revision ID: 20260725_0007
Revises: 20260614_0006
Create Date: 2026-07-25
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "20260725_0007"
down_revision: str | None = "20260614_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _execute(sql: str) -> None:
    op.execute(sql)


def upgrade() -> None:
    _execute("SET LOCAL ROLE eva_owner")
    _execute(
        """
        CREATE TABLE archive.alert_feedback (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id uuid NOT NULL,
            detection_id bigint NOT NULL CHECK (detection_id > 0),
            channel_id bigint NOT NULL CHECK (channel_id > 0),
            alert_timestamp_ms bigint NOT NULL CHECK (alert_timestamp_ms >= 0),
            actor_id uuid NOT NULL,
            reason_code text NOT NULL,
            note text,
            alert_title text NOT NULL,
            alert_snapshot jsonb NOT NULL
                CHECK (jsonb_typeof(alert_snapshot) = 'object'),
            submitted_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
            UNIQUE (tenant_id, id),
            UNIQUE (tenant_id, detection_id, actor_id),
            CHECK (
                reason_code IN (
                    'no_relevant_event',
                    'benign_activity',
                    'wrong_object_or_actor',
                    'duplicate_or_stale',
                    'poor_visual_quality'
                )
            ),
            CHECK (alert_title = btrim(alert_title) AND alert_title <> ''),
            CHECK (length(alert_title) <= 160),
            CHECK (note IS NULL OR length(note) <= 1000)
        )
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_alert_feedback_alert_time
        ON archive.alert_feedback (
            tenant_id,
            alert_timestamp_ms DESC,
            id DESC
        )
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_alert_feedback_channel_time
        ON archive.alert_feedback (
            tenant_id,
            channel_id,
            alert_timestamp_ms DESC
        )
        """
    )
    _execute(
        """
        CREATE INDEX ix_archive_alert_feedback_reason_time
        ON archive.alert_feedback (
            tenant_id,
            reason_code,
            alert_timestamp_ms DESC
        )
        """
    )
    _execute("ALTER TABLE archive.alert_feedback ENABLE ROW LEVEL SECURITY")
    _execute("ALTER TABLE archive.alert_feedback FORCE ROW LEVEL SECURITY")
    _execute(
        """
        CREATE POLICY archive_alert_feedback_tenant_isolation
        ON archive.alert_feedback
        USING (
            tenant_id = NULLIF(current_setting('eva.tenant_id', true), '')::uuid
        )
        WITH CHECK (
            tenant_id = NULLIF(current_setting('eva.tenant_id', true), '')::uuid
        )
        """
    )
    _execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON archive.alert_feedback "
        "TO eva_api, eva_worker"
    )
    _execute(
        "GRANT SELECT ON archive.alert_feedback "
        "TO eva_agent_reader, eva_backup"
    )
    _execute(
        "GRANT USAGE, SELECT ON SEQUENCE archive.alert_feedback_id_seq "
        "TO eva_api, eva_worker"
    )
    _execute(
        "GRANT SELECT ON SEQUENCE archive.alert_feedback_id_seq TO eva_backup"
    )
    _execute("RESET ROLE")


def downgrade() -> None:
    _execute("SET LOCAL ROLE eva_owner")
    _execute("DROP TABLE IF EXISTS archive.alert_feedback")
    _execute("RESET ROLE")
