#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from config import Config
from luxriot_connector import LuxriotClient
from road_events import MotionAnalyzerConfig, RoadSceneCard, RoadZone, load_scene_cards
from road_events.runner import RoadCvChannelConfig, RoadCvRunner
from road_events.video import DecodedVideoFrame


def _resolve_channel(client: LuxriotClient, channel_ref: str) -> tuple[int, str]:
    ref = str(channel_ref or "").strip()
    if not ref:
        raise SystemExit("channel is required")
    channels = client.get_channels()
    if ref.isdigit():
        channel_id = int(ref)
        for channel in channels:
            if channel.get("id") == channel_id:
                return channel_id, str(channel.get("title") or f"Channel {channel_id}")
        return channel_id, f"Channel {channel_id}"
    lowered = ref.lower()
    matches = [
        channel
        for channel in channels
        if lowered in str(channel.get("title") or "").lower()
    ]
    if not matches:
        titles = ", ".join(f"{item.get('id')}:{item.get('title')}" for item in channels)
        raise SystemExit(f"channel {ref!r} not found. Available: {titles}")
    if len(matches) > 1:
        titles = ", ".join(f"{item.get('id')}:{item.get('title')}" for item in matches)
        raise SystemExit(f"channel {ref!r} is ambiguous: {titles}")
    channel = matches[0]
    return int(channel["id"]), str(channel.get("title") or f"Channel {channel['id']}")


def _fallback_scene(channel_id: int, title: str) -> RoadSceneCard:
    return RoadSceneCard(
        channel_id=channel_id,
        title=title,
        zones=(
            RoadZone(
                name="full_frame",
                polygon=((0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)),
                expected_flow=None,
            ),
        ),
        notes="Generated by road_cv_luxriot_snapshot_smoke.py because no scene-card file was provided.",
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run road-CV smoke against Luxriot snapshot API for one live channel."
    )
    parser.add_argument("--channel", required=True, help="Channel id or unique title substring, e.g. 118 or emu-1")
    parser.add_argument("--stream", default="mainStream")
    parser.add_argument("--frames", type=int, default=24)
    parser.add_argument("--interval-sec", type=float, default=0.5)
    parser.add_argument("--scene-cards", default="", help="JSON scene-card file; falls back to full-frame zone")
    parser.add_argument("--max-edge", type=int, default=360)
    parser.add_argument("--min-motion-px", type=float, default=0.7)
    parser.add_argument("--active-ratio-floor", type=float, default=0.012)
    parser.add_argument("--save-dir", default="", help="Optional directory for captured JPEG snapshots")
    parser.add_argument("--jsonl", action="store_true", help="Print recent cues/episodes as JSON lines")
    args = parser.parse_args()

    client = LuxriotClient(Config.LUXRIOT_BASE_URL, Config.LUXRIOT_USERNAME, Config.LUXRIOT_PASSWORD)
    channel_id, channel_title = _resolve_channel(client, args.channel)
    if args.scene_cards:
        cards = load_scene_cards(args.scene_cards)
        if channel_id not in cards:
            raise SystemExit(f"channel {channel_id} is not present in {args.scene_cards}")
        scene = cards[channel_id]
    else:
        scene = _fallback_scene(channel_id, channel_title)

    save_dir = Path(args.save_dir).expanduser() if args.save_dir else None
    if save_dir:
        save_dir.mkdir(parents=True, exist_ok=True)

    def frame_iter(_source, **kwargs):
        max_frames = int(kwargs.get("max_frames") or args.frames)
        for index in range(max(1, max_frames)):
            image = client.get_snapshot(channel_id, stream=args.stream)
            timestamp_ms = int(time.time() * 1000)
            if save_dir:
                image.save(save_dir / f"ch{channel_id}-{index:04d}.jpg", quality=90)
            yield DecodedVideoFrame(
                frame_index=index,
                timestamp_ms=timestamp_ms,
                image=image,
                source_timestamp_ms=timestamp_ms,
            )
            if index + 1 < max_frames:
                time.sleep(max(0.05, float(args.interval_sec)))

    runner = RoadCvRunner(
        RoadCvChannelConfig(
            channel_id=channel_id,
            source=f"luxriot-snapshot:{channel_id}",
            scene_card=scene,
            motion_config=MotionAnalyzerConfig(
                max_edge=args.max_edge,
                min_motion_px=args.min_motion_px,
                active_ratio_floor=args.active_ratio_floor,
            ),
        ),
        frame_iter_factory=frame_iter,
    )
    status = runner.run_once(max_frames=max(1, int(args.frames)))
    payload = runner.status_dict()
    payload["channel_title"] = channel_title
    payload["scene"] = {
        "channel_id": scene.channel_id,
        "title": scene.title,
        "zones": [zone.name for zone in scene.active_zones()],
    }
    if save_dir:
        payload["saved_snapshots_dir"] = str(save_dir)
    if args.jsonl:
        for cue in status.recent_cues:
            print(json.dumps({"type": "cue", **cue}, ensure_ascii=False))
        for episode in status.recent_episodes:
            print(json.dumps({"type": "episode", **episode}, ensure_ascii=False))
    else:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0 if not status.last_error else 2


if __name__ == "__main__":
    raise SystemExit(main())
