#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from road_events import MotionAnalyzerConfig, RoadSceneCard, RoadZone, load_scene_cards
from road_events.runner import RoadCvChannelConfig, RoadCvRunner


def _source(value: str) -> str | int:
    stripped = value.strip()
    if stripped.isdigit():
        return int(stripped)
    return stripped


def _fallback_scene(channel_id: int) -> RoadSceneCard:
    return RoadSceneCard(
        channel_id=channel_id,
        title="full-frame smoke scene",
        zones=(
            RoadZone(
                name="full_frame",
                polygon=((0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)),
                expected_flow=None,
            ),
        ),
        notes="Generated by road_cv_smoke.py because no scene-card file was provided.",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the experimental road-CV primitive on one source.")
    parser.add_argument("--source", required=True, help="OpenCV source: file path, RTSP URL, HTTP URL, or device index")
    parser.add_argument("--channel-id", type=int, required=True)
    parser.add_argument("--scene-cards", default="", help="JSON scene-card file; falls back to full-frame zone")
    parser.add_argument("--max-frames", type=int, default=120)
    parser.add_argument("--every-n", type=int, default=1)
    parser.add_argument("--max-edge", type=int, default=360)
    parser.add_argument("--min-motion-px", type=float, default=0.7)
    parser.add_argument("--active-ratio-floor", type=float, default=0.012)
    parser.add_argument("--jsonl", action="store_true", help="Print recent cues/episodes as JSON lines")
    args = parser.parse_args()

    if args.scene_cards:
        cards = load_scene_cards(args.scene_cards)
        if args.channel_id not in cards:
            raise SystemExit(f"channel {args.channel_id} is not present in {args.scene_cards}")
        scene = cards[args.channel_id]
    else:
        scene = _fallback_scene(args.channel_id)

    runner = RoadCvRunner(
        RoadCvChannelConfig(
            channel_id=args.channel_id,
            source=_source(args.source),
            scene_card=scene,
            every_n=max(1, args.every_n),
            motion_config=MotionAnalyzerConfig(
                max_edge=args.max_edge,
                min_motion_px=args.min_motion_px,
                active_ratio_floor=args.active_ratio_floor,
            ),
        )
    )
    status = runner.run_once(max_frames=max(1, args.max_frames))
    payload = runner.status_dict()
    payload["scene"] = {
        "channel_id": scene.channel_id,
        "title": scene.title,
        "zones": [zone.name for zone in scene.active_zones()],
    }
    if args.jsonl:
        for cue in status.recent_cues:
            print(json.dumps({"type": "cue", **cue}, ensure_ascii=False))
        for episode in status.recent_episodes:
            print(json.dumps({"type": "episode", **episode}, ensure_ascii=False))
    else:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0 if not status.last_error else 2


if __name__ == "__main__":
    raise SystemExit(main())
