#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from config import Config
from luxriot_connector import LuxriotClient
from road_events import (
    AutoSceneCardConfig,
    MotionAnalyzerConfig,
    RoadCvChannelConfig,
    RoadCvRunner,
    RoadSceneCard,
    RoadZone,
    infer_scene_card_from_frames,
    iter_luxriot_archive_segment_frames,
    iter_luxriot_archive_snapshots,
    iter_luxriot_live_segment_frames,
    load_scene_cards,
)


def _resolve_channel(client: LuxriotClient, channel_ref: str) -> tuple[int, str]:
    ref = str(channel_ref or "").strip()
    if not ref:
        raise SystemExit("channel is required")
    channels = client.get_channels()
    if ref.isdigit():
        channel_id = int(ref)
        for channel in channels:
            if channel.get("id") == channel_id:
                return channel_id, str(channel.get("title") or f"Channel {channel_id}")
        return channel_id, f"Channel {channel_id}"
    lowered = ref.lower()
    matches = [
        channel
        for channel in channels
        if lowered in str(channel.get("title") or "").lower()
    ]
    if not matches:
        titles = ", ".join(f"{item.get('id')}:{item.get('title')}" for item in channels)
        raise SystemExit(f"channel {ref!r} not found. Available: {titles}")
    if len(matches) > 1:
        titles = ", ".join(f"{item.get('id')}:{item.get('title')}" for item in matches)
        raise SystemExit(f"channel {ref!r} is ambiguous: {titles}")
    channel = matches[0]
    return int(channel["id"]), str(channel.get("title") or f"Channel {channel['id']}")


def _fallback_scene(channel_id: int, title: str) -> RoadSceneCard:
    return RoadSceneCard(
        channel_id=channel_id,
        title=title,
        zones=(
            RoadZone(
                name="full_frame",
                polygon=((0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)),
                expected_flow=None,
            ),
        ),
        notes="Generated by road_cv_luxriot_api_smoke.py because no scene-card file was provided.",
    )


def _archive_window(
    client: LuxriotClient,
    channel_id: int,
    *,
    stream_type: str,
    start_ms: int | None,
    end_ms: int | None,
    last_minutes: float,
) -> tuple[int, int, dict]:
    boundaries = client.get_archive_boundaries(channel_id, stream_type=stream_type)
    main = boundaries.get("main") or boundaries.get("use") or {}
    archive_start = int(main.get("from") or 0)
    archive_end = int(main.get("to") or 0)
    if archive_start <= 0 or archive_end <= 0 or archive_end < archive_start:
        raise SystemExit(f"channel {channel_id} has no archive boundaries for {stream_type}: {boundaries}")
    resolved_end = int(end_ms) if end_ms is not None else archive_end
    resolved_start = int(start_ms) if start_ms is not None else max(
        archive_start,
        resolved_end - int(max(0.1, float(last_minutes)) * 60_000),
    )
    resolved_start = max(archive_start, resolved_start)
    resolved_end = min(archive_end, resolved_end)
    if resolved_end < resolved_start:
        raise SystemExit(
            f"resolved archive window is empty: {resolved_start}..{resolved_end}, boundaries={boundaries}"
        )
    return resolved_start, resolved_end, boundaries


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run road-CV smoke against Luxriot live-video or archive-snapshot APIs."
    )
    parser.add_argument("--channel", required=True, help="Channel id or unique title substring, e.g. 118 or emu-1")
    parser.add_argument(
        "--mode",
        choices=("live-video", "archive-snapshots", "archive-video"),
        default="archive-snapshots",
    )
    parser.add_argument("--stream", default="mainStream")
    parser.add_argument("--scene-cards", default="", help="JSON scene-card file; falls back to full-frame zone")
    parser.add_argument("--auto-scene", action="store_true", help="Infer a scene-card from a bounded motion-history sample")
    parser.add_argument("--auto-scene-frames", type=int, default=80)
    parser.add_argument("--frames", type=int, default=120)
    parser.add_argument("--every-n", type=int, default=1)
    parser.add_argument("--max-edge", type=int, default=360)
    parser.add_argument("--min-motion-px", type=float, default=0.7)
    parser.add_argument("--active-ratio-floor", type=float, default=0.012)
    parser.add_argument("--jsonl", action="store_true", help="Print recent cues/episodes as JSON lines")
    parser.add_argument("--start-ms", type=int, default=None, help="Archive start epoch ms")
    parser.add_argument("--end-ms", type=int, default=None, help="Archive end epoch ms")
    parser.add_argument("--last-minutes", type=float, default=10.0, help="Archive lookback when start/end are omitted")
    parser.add_argument("--interval-ms", type=int, default=1000, help="Archive snapshot sampling interval")
    parser.add_argument("--segment-mb", type=float, default=4.0, help="Live video capture budget")
    parser.add_argument("--segment-sec", type=float, default=15.0, help="Live/archive video capture wall-clock budget")
    parser.add_argument("--keep-segment", default="", help="Optional path to keep the captured live MP4 segment")
    parser.add_argument("--keep-segment-dir", default="", help="Optional directory to keep captured archive MP4 chunks")
    args = parser.parse_args()

    client = LuxriotClient(Config.LUXRIOT_BASE_URL, Config.LUXRIOT_USERNAME, Config.LUXRIOT_PASSWORD)
    channel_id, channel_title = _resolve_channel(client, args.channel)
    scene = None
    if args.scene_cards:
        cards = load_scene_cards(args.scene_cards)
        if channel_id not in cards:
            raise SystemExit(f"channel {channel_id} is not present in {args.scene_cards}")
        scene = cards[channel_id]

    metadata: dict[str, object] = {
        "mode": args.mode,
        "channel_title": channel_title,
        "stream": args.stream,
    }
    if args.mode in {"archive-snapshots", "archive-video"}:
        start_ms, end_ms, boundaries = _archive_window(
            client,
            channel_id,
            stream_type=args.stream,
            start_ms=args.start_ms,
            end_ms=args.end_ms,
            last_minutes=args.last_minutes,
        )
        metadata.update(
            {
                "archive_start_ms": start_ms,
                "archive_end_ms": end_ms,
                "archive_boundaries": boundaries,
                "interval_ms": max(1, int(args.interval_ms)),
            }
        )
    def _archive_snapshot_iter(frame_limit: int):
        return iter_luxriot_archive_snapshots(
            client,
            channel_id,
            start_ms=start_ms,
            end_ms=end_ms,
            interval_ms=max(1, int(args.interval_ms)),
            stream_type=args.stream,
            max_frames=frame_limit,
        )

    def _archive_video_iter(frame_limit: int):
        return iter_luxriot_archive_segment_frames(
            client,
            channel_id,
            start_ms=start_ms,
            end_ms=end_ms,
            stream_type=args.stream,
            segment_bytes=int(max(0.1, float(args.segment_mb)) * 1024 * 1024),
            segment_seconds=max(0.25, float(args.segment_sec)),
            every_n=max(1, int(args.every_n)),
            max_frames=frame_limit,
            keep_segment_dir=Path(args.keep_segment_dir).expanduser() if args.keep_segment_dir else None,
        )

    def _live_video_iter(frame_limit: int):
        return iter_luxriot_live_segment_frames(
            client,
            channel_id,
            stream=args.stream,
            segment_bytes=int(max(0.1, float(args.segment_mb)) * 1024 * 1024),
            segment_seconds=max(0.25, float(args.segment_sec)),
            every_n=max(1, int(args.every_n)),
            max_frames=frame_limit,
            keep_segment_path=Path(args.keep_segment).expanduser() if args.keep_segment else None,
        )

    if scene is None and args.auto_scene:
        auto_frame_limit = max(2, int(args.auto_scene_frames))
        if args.mode == "archive-snapshots":
            auto_frames = list(_archive_snapshot_iter(auto_frame_limit))
        elif args.mode == "archive-video":
            auto_frames = list(_archive_video_iter(auto_frame_limit))
        else:
            auto_frames = list(_live_video_iter(auto_frame_limit))
        auto_result = infer_scene_card_from_frames(
            channel_id,
            channel_title,
            auto_frames,
            config=AutoSceneCardConfig(max_edge=max(96, min(360, int(args.max_edge)))),
        )
        scene = auto_result.scene_card
        metadata["auto_scene"] = auto_result.as_dict()
    elif scene is None:
        scene = _fallback_scene(channel_id, channel_title)
        metadata["auto_scene"] = {
            "confidence": "low",
            "reason": "disabled; using full-frame fallback",
        }

    if args.mode == "archive-snapshots":

        def frame_iter(_source, **kwargs):
            return _archive_snapshot_iter(int(kwargs.get("max_frames") or args.frames))

        source = f"luxriot-archive-snapshots:{channel_id}:{start_ms}-{end_ms}"
    elif args.mode == "archive-video":
        segment_bytes = int(max(0.1, float(args.segment_mb)) * 1024 * 1024)
        keep_segment_dir = Path(args.keep_segment_dir).expanduser() if args.keep_segment_dir else None
        metadata.update(
            {
                "segment_bytes": segment_bytes,
                "segment_sec": max(0.25, float(args.segment_sec)),
                "keep_segment_dir": str(keep_segment_dir) if keep_segment_dir else "",
            }
        )

        def frame_iter(_source, **kwargs):
            return _archive_video_iter(int(kwargs.get("max_frames") or args.frames))

        source = f"luxriot-archive-video:{channel_id}:{start_ms}-{end_ms}"
    else:
        segment_bytes = int(max(0.1, float(args.segment_mb)) * 1024 * 1024)
        keep_segment = Path(args.keep_segment).expanduser() if args.keep_segment else None
        metadata.update(
            {
                "segment_bytes": segment_bytes,
                "segment_sec": max(0.25, float(args.segment_sec)),
                "keep_segment": str(keep_segment) if keep_segment else "",
            }
        )

        def frame_iter(_source, **kwargs):
            return _live_video_iter(int(kwargs.get("max_frames") or args.frames))

        source = f"luxriot-live-video:{channel_id}:{args.stream}"

    runner = RoadCvRunner(
        RoadCvChannelConfig(
            channel_id=channel_id,
            source=source,
            scene_card=scene,
            every_n=max(1, int(args.every_n)),
            motion_config=MotionAnalyzerConfig(
                max_edge=args.max_edge,
                min_motion_px=args.min_motion_px,
                active_ratio_floor=args.active_ratio_floor,
            ),
        ),
        frame_iter_factory=frame_iter,
    )
    status = runner.run_once(max_frames=max(1, int(args.frames)))
    payload = runner.status_dict()
    payload.update(metadata)
    payload["scene"] = {
        "channel_id": scene.channel_id,
        "title": scene.title,
        "zones": [zone.name for zone in scene.active_zones()],
        "zone_details": [
            {
                "name": zone.name,
                "zone_type": zone.zone_type,
                "expected_flow": list(zone.expected_flow) if zone.expected_flow else None,
                "polygon": [list(point) for point in zone.polygon],
            }
            for zone in scene.active_zones()
        ],
        "notes": scene.notes,
    }
    if args.jsonl:
        for cue in status.recent_cues:
            print(json.dumps({"type": "cue", **cue}, ensure_ascii=False))
        for episode in status.recent_episodes:
            print(json.dumps({"type": "episode", **episode}, ensure_ascii=False))
    else:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0 if not status.last_error else 2


if __name__ == "__main__":
    raise SystemExit(main())
