#!/usr/bin/env python3
"""Capture and validate the UI screenshots used by the operator/admin guides.

Every screenshot under `docs/ui/assets/` is produced from a scene declared in
`docs/ui/shots.json` — no hand-taken screenshots, so a guide picture can always
be regenerated by a person or an assistant without guessing what was clicked.

Two halves with very different requirements:

  validate / list   stdlib only, no browser, no network, no running service.
                    This is the CI gate (called from scripts/check_docs_drift.sh).
  capture           needs requirements-docs.txt (Playwright) and a running EVA.
                    Workstation-only; the appliance never ships a browser driver.

Privacy: evidence frames are operational camera data and must never land in a
committed PNG. The default `media_policy` is `placeholder`, which intercepts the
evidence-image endpoints in the browser so real pixels are never decoded, and
additionally blurs elements the network layer cannot neutralize (video/canvas).
`pass` (real media, no redaction) exists for a deployment running deliberately
neutral streams and requires an explicit --allow-real-media flag; the choice is
recorded in each screenshot's sidecar so review can see it.

Usage:
    python scripts/ui_shots.py validate
    python scripts/ui_shots.py list
    python scripts/ui_shots.py capture --base-url http://127.0.0.1:5000
    python scripts/ui_shots.py capture --scene legacy-video-tab --check
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "docs" / "ui" / "shots.json"
ASSET_DIR_REL = "docs/ui/assets"
DOC_ROOT = REPO_ROOT / "docs"

TOOL_ID = "ui_shots.py/1"
SCENE_ID_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
MARKDOWN_IMAGE_RE = re.compile(r"!\[[^\]]*\]\(([^)\s]+)")

VALID_UIS = {"legacy", "react"}
VALID_ROLES = {"none", "viewer", "operator", "engineer", "admin"}
VALID_MEDIA_POLICIES = {"placeholder", "blur", "pass"}

# Endpoints that serve operational evidence imagery. `placeholder` mode fulfils
# these with a neutral graphic instead of letting the browser fetch them.
EVIDENCE_URL_PATTERNS = (
    "**/detections/image*",
    "**/detections/thumbnail/**",
    "**/image/**",
)

# Files whose content determines what a screenshot looks like. Recorded per
# scene so `validate` can flag a picture that predates a UI change.
# Sources, not build output: `react-ui/dist` is gitignored and absent on a machine
# that only validates, which would make every scene look stale.
FINGERPRINT_SOURCES = {
    "legacy": ("templates/index.html", "static/js/app.js", "static/css"),
    "react": ("react-ui/src", "react-ui/index.html"),
}

STEP_VERBS = {
    "click": str,
    "wait_for": str,
    "wait_ms": int,
    "hide": str,
    "scroll_to": str,
    "fill": dict,
    "set_text": dict,
    "press": dict,
}

DETERMINISM_CSS = """
*, *::before, *::after {
  animation-duration: 0s !important;
  animation-delay: 0s !important;
  transition-duration: 0s !important;
  transition-delay: 0s !important;
  caret-color: transparent !important;
}
html { scrollbar-width: none !important; }
::-webkit-scrollbar { display: none !important; }
"""

PLACEHOLDER_SVG = (
    "<svg xmlns='http://www.w3.org/2000/svg' width='640' height='360'>"
    "<defs><pattern id='h' width='16' height='16' patternUnits='userSpaceOnUse'"
    " patternTransform='rotate(45)'>"
    "<rect width='16' height='16' fill='#1b1f27'/>"
    "<line x1='0' y1='0' x2='0' y2='16' stroke='#2c333f' stroke-width='8'/>"
    "</pattern></defs>"
    "<rect width='640' height='360' fill='url(#h)'/>"
    "<text x='320' y='188' fill='#7c8798' font-family='sans-serif' font-size='22'"
    " text-anchor='middle'>evidence frame withheld</text>"
    "</svg>"
)


class ManifestError(Exception):
    """The manifest could not be read or is structurally unusable."""


# --------------------------------------------------------------------------
# manifest
# --------------------------------------------------------------------------


def load_manifest(path: Path = MANIFEST_PATH) -> Dict[str, Any]:
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ManifestError(f"cannot read manifest {path}: {exc}") from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ManifestError(f"{path} is not valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ManifestError(f"{path} must contain a JSON object")
    if not isinstance(data.get("scenes"), list):
        raise ManifestError(f"{path} must contain a 'scenes' array")
    return data


def scene_defaults(manifest: Dict[str, Any]) -> Dict[str, Any]:
    defaults = manifest.get("defaults") or {}
    return defaults if isinstance(defaults, dict) else {}


def resolve(scene: Dict[str, Any], defaults: Dict[str, Any], key: str, fallback: Any = None) -> Any:
    if key in scene:
        return scene[key]
    return defaults.get(key, fallback)


def enabled_scenes(manifest: Dict[str, Any]) -> List[Dict[str, Any]]:
    return [s for s in manifest["scenes"] if s.get("enabled", True)]


# --------------------------------------------------------------------------
# validation
# --------------------------------------------------------------------------


class Problems:
    """Collected findings, split into blocking errors and advisory warnings."""

    def __init__(self) -> None:
        self.errors: List[str] = []
        self.warnings: List[str] = []
        self.info: List[str] = []

    def error(self, message: str) -> None:
        self.errors.append(message)

    def warn(self, message: str) -> None:
        self.warnings.append(message)

    def note(self, message: str) -> None:
        self.info.append(message)

    def report(self, strict: bool) -> int:
        for message in self.info:
            print(f"ui shots: {message}")
        for message in self.warnings:
            print(f"ui shots WARN: {message}")
        for message in self.errors:
            print(f"ui shots ERROR: {message}")
        if self.errors:
            return 1
        if strict and self.warnings:
            print("ui shots: --strict, warnings are fatal")
            return 1
        print("ui shots check: OK")
        return 0


def _validate_step(step: Any, where: str, problems: Problems) -> None:
    if not isinstance(step, dict):
        problems.error(f"{where}: step must be an object, got {type(step).__name__}")
        return
    verbs = [key for key in step if key in STEP_VERBS]
    unknown = [key for key in step if key not in STEP_VERBS and not key.startswith("_")]
    if unknown:
        problems.error(f"{where}: unknown step verb(s) {unknown}; allowed: {sorted(STEP_VERBS)}")
    if len(verbs) != 1:
        problems.error(f"{where}: a step needs exactly one verb, found {verbs or 'none'}")
        return
    verb = verbs[0]
    value = step[verb]
    expected = STEP_VERBS[verb]
    if expected is int:
        if not isinstance(value, int) or isinstance(value, bool) or value < 0:
            problems.error(f"{where}: '{verb}' needs a non-negative integer")
        elif value > 30000:
            problems.warn(f"{where}: '{verb}' waits {value} ms; scenes should stay quick")
    elif expected is str:
        if not isinstance(value, str) or not value.strip():
            problems.error(f"{where}: '{verb}' needs a non-empty selector string")
    elif expected is dict:
        if not isinstance(value, dict):
            problems.error(f"{where}: '{verb}' needs an object")
            return
        required = {"fill": ("selector", "value"), "set_text": ("selector", "value"), "press": ("selector", "key")}[verb]
        for field in required:
            if not isinstance(value.get(field), str) or not value[field].strip():
                problems.error(f"{where}: '{verb}' needs a non-empty '{field}' string")


def _validate_scene(scene: Any, index: int, defaults: Dict[str, Any], seen_ids: set, seen_outputs: set,
                    problems: Problems) -> None:
    where = f"scene[{index}]"
    if not isinstance(scene, dict):
        problems.error(f"{where}: must be an object")
        return
    scene_id = scene.get("id")
    if not isinstance(scene_id, str) or not SCENE_ID_RE.match(scene_id):
        problems.error(f"{where}: 'id' must be kebab-case, got {scene_id!r}")
        return
    where = f"scene '{scene_id}'"
    if scene_id in seen_ids:
        problems.error(f"{where}: duplicate id")
    seen_ids.add(scene_id)

    if scene.get("ui") not in VALID_UIS:
        problems.error(f"{where}: 'ui' must be one of {sorted(VALID_UIS)}")
    if scene.get("auth", "none") not in VALID_ROLES:
        problems.error(f"{where}: 'auth' must be one of {sorted(VALID_ROLES)}")
    if not isinstance(scene.get("path"), str) or not scene["path"].startswith("/"):
        problems.error(f"{where}: 'path' must be a root-relative URL path")
    for field in ("title", "caption"):
        if not isinstance(scene.get(field), str) or not scene[field].strip():
            problems.error(f"{where}: '{field}' is required (the caption becomes the alt text)")

    policy = resolve(scene, defaults, "media_policy", "placeholder")
    if policy not in VALID_MEDIA_POLICIES:
        problems.error(f"{where}: 'media_policy' must be one of {sorted(VALID_MEDIA_POLICIES)}")

    output = scene.get("output")
    if not isinstance(output, str):
        problems.error(f"{where}: 'output' is required")
    else:
        if not output.startswith(ASSET_DIR_REL + "/") or not output.endswith(".png"):
            problems.error(f"{where}: 'output' must be a .png under {ASSET_DIR_REL}/")
        if output in seen_outputs:
            problems.error(f"{where}: duplicate output path {output}")
        seen_outputs.add(output)

    steps = scene.get("steps", [])
    if not isinstance(steps, list):
        problems.error(f"{where}: 'steps' must be an array")
    else:
        for step_index, step in enumerate(steps):
            _validate_step(step, f"{where} step[{step_index}]", problems)

    clip = scene.get("clip")
    if clip is not None and (not isinstance(clip, str) or not clip.strip()):
        problems.error(f"{where}: 'clip' must be null or a non-empty selector")

    used_by = scene.get("used_by", [])
    if not isinstance(used_by, list) or any(not isinstance(item, str) for item in used_by):
        problems.error(f"{where}: 'used_by' must be an array of doc paths")
    else:
        for doc in used_by:
            if not (REPO_ROOT / doc).is_file():
                problems.error(f"{where}: used_by references missing doc {doc}")


def scan_doc_image_references() -> Dict[str, List[str]]:
    """Map each committed asset path -> docs that embed it (markdown image syntax)."""
    references: Dict[str, List[str]] = {}
    for doc in sorted(DOC_ROOT.rglob("*.md")):
        try:
            text = doc.read_text(encoding="utf-8")
        except OSError:
            continue
        for match in MARKDOWN_IMAGE_RE.finditer(text):
            target = match.group(1).split("#")[0]
            if "ui/assets/" not in target:
                continue
            resolved = (doc.parent / target).resolve()
            try:
                rel = resolved.relative_to(REPO_ROOT).as_posix()
            except ValueError:
                rel = resolved.as_posix()
            references.setdefault(rel, []).append(doc.relative_to(REPO_ROOT).as_posix())
    return references


def _hash_path(path: Path) -> Optional[str]:
    digest = hashlib.sha256()
    if path.is_file():
        digest.update(path.read_bytes())
    elif path.is_dir():
        for child in sorted(path.rglob("*")):
            if child.is_file():
                digest.update(child.relative_to(path).as_posix().encode())
                digest.update(child.read_bytes())
    else:
        return None
    return digest.hexdigest()[:16]


def source_fingerprint(ui: str) -> Dict[str, Optional[str]]:
    return {rel: _hash_path(REPO_ROOT / rel) for rel in FINGERPRINT_SOURCES.get(ui, ())}


def sidecar_path(output_rel: str) -> Path:
    return REPO_ROOT / (output_rel + ".meta.json")


SELECTOR_TOKEN_RE = re.compile(r"[.#]([A-Za-z][\w-]*)")
HAS_TEXT_RE = re.compile(r":has-text\((['\"])(.*?)\1\)")


def selector_tokens(selector: str) -> List[str]:
    """Class and id names referenced by a selector, ignoring :has-text() literals."""
    return SELECTOR_TOKEN_RE.findall(HAS_TEXT_RE.sub("", selector))


def scene_selectors(scene: Dict[str, Any]) -> List[str]:
    selectors: List[str] = []
    clip = scene.get("clip")
    if isinstance(clip, str):
        selectors.append(clip)
    for step in scene.get("steps", []) or []:
        if not isinstance(step, dict):
            continue
        for verb in ("click", "wait_for", "hide", "scroll_to"):
            if isinstance(step.get(verb), str):
                selectors.append(step[verb])
        for verb in ("fill", "set_text", "press"):
            payload = step.get(verb)
            if isinstance(payload, dict) and isinstance(payload.get("selector"), str):
                selectors.append(payload["selector"])
    return selectors


def ui_source_text(ui: str) -> str:
    """Concatenated UI sources, used to sanity-check that a selector's names exist."""
    chunks: List[str] = []
    for rel in FINGERPRINT_SOURCES.get(ui, ()):
        path = REPO_ROOT / rel
        if path.is_file():
            chunks.append(path.read_text(encoding="utf-8", errors="ignore"))
        elif path.is_dir():
            for child in sorted(path.rglob("*")):
                if child.is_file() and child.suffix in {".tsx", ".ts", ".jsx", ".js", ".html", ".css"}:
                    chunks.append(child.read_text(encoding="utf-8", errors="ignore"))
    return "\n".join(chunks)


def lint_selectors(manifest: Dict[str, Any], problems: Problems) -> None:
    """Warn about class/id names no UI source mentions — a typo caught without a browser.

    Only a spelling check: a name that exists somewhere may still be the wrong
    element, and a name assembled at runtime may be missed. It is cheap and it
    catches the mistake that would otherwise waste a whole capture session.
    """
    cache: Dict[str, str] = {}
    for scene in manifest["scenes"]:
        ui = scene.get("ui")
        if ui not in FINGERPRINT_SOURCES:
            continue
        if ui not in cache:
            cache[ui] = ui_source_text(ui)
        source = cache[ui]
        if not source:
            continue
        unknown = sorted({
            token
            for selector in scene_selectors(scene)
            for token in selector_tokens(selector)
            if not re.search(rf"\b{re.escape(token)}\b", source)
        })
        if unknown:
            problems.warn(
                f"scene '{scene.get('id')}': no {ui} source mentions {', '.join(unknown)}"
            )


def validate(manifest: Dict[str, Any], strict: bool = False) -> int:
    problems = Problems()
    defaults = scene_defaults(manifest)
    seen_ids: set = set()
    seen_outputs: set = set()

    for index, scene in enumerate(manifest["scenes"]):
        _validate_scene(scene, index, defaults, seen_ids, seen_outputs, problems)

    lint_selectors(manifest, problems)

    references = scan_doc_image_references()
    for target, docs in sorted(references.items()):
        if not (REPO_ROOT / target).is_file():
            problems.error(f"{docs[0]} embeds missing screenshot {target} (run: ui_shots.py capture)")
        elif target not in seen_outputs:
            problems.error(f"{docs[0]} embeds {target}, which no scene in docs/ui/shots.json produces")

    asset_dir = REPO_ROOT / ASSET_DIR_REL
    if asset_dir.is_dir():
        for png in sorted(asset_dir.glob("*.png")):
            rel = png.relative_to(REPO_ROOT).as_posix()
            if rel not in seen_outputs:
                problems.error(f"orphan screenshot {rel}: no scene produces it (delete it or add a scene)")

    pending: List[str] = []
    for scene in manifest["scenes"]:
        output = scene.get("output")
        if not isinstance(output, str):
            continue
        if not scene.get("enabled", True):
            continue
        path = REPO_ROOT / output
        if not path.is_file():
            pending.append(scene.get("id", output))
            continue
        if output not in references:
            problems.warn(f"{output} is captured but no doc embeds it yet")
        meta_path = sidecar_path(output)
        if not meta_path.is_file():
            problems.warn(f"{output} has no {meta_path.name}; recapture to record its provenance")
            continue
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            problems.error(f"{meta_path.name}: unreadable ({exc})")
            continue
        if meta.get("media_policy") == "pass":
            problems.warn(
                f"{output} was captured with media_policy=pass (real media); "
                "confirm the source streams are rights-cleared and non-personal"
            )
        current = source_fingerprint(scene.get("ui", "legacy"))
        recorded = meta.get("source_fingerprint") or {}
        changed = [key for key, value in current.items() if recorded.get(key) != value]
        if changed:
            problems.warn(f"{output} predates changes in {', '.join(changed)}; recapture the scene")

    if pending:
        problems.note(f"{len(pending)} scene(s) not captured yet: {', '.join(sorted(pending))}")

    disabled = [s.get("id") for s in manifest["scenes"] if not s.get("enabled", True)]
    if disabled:
        problems.note(f"{len(disabled)} scene(s) disabled: {', '.join(str(d) for d in disabled)}")

    return problems.report(strict)


# --------------------------------------------------------------------------
# capture
# --------------------------------------------------------------------------


def credentials_for(role: str) -> Optional[Tuple[str, str]]:
    if role == "none":
        return None
    prefix = f"EVA_SHOTS_{role.upper()}_"
    user = os.getenv(prefix + "USER") or os.getenv("EVA_SHOTS_USER")
    password = os.getenv(prefix + "PASSWORD") or os.getenv("EVA_SHOTS_PASSWORD")
    if user and password:
        return user, password
    return None


def login_cookies(base_url: str, username: str, password: str, verify_tls: bool) -> List[Dict[str, Any]]:
    """Authenticate over the same POST /auth/login the UI uses, return browser cookies."""
    import requests  # already a runtime dependency; imported lazily for the stdlib-only paths
    import urllib3

    if not verify_tls:
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    session = requests.Session()
    session.verify = verify_tls
    response = session.post(
        base_url.rstrip("/") + "/auth/login",
        json={"username": username, "password": password},
        timeout=30,
    )
    response.raise_for_status()

    from urllib.parse import urlparse

    host = urlparse(base_url).hostname or "127.0.0.1"
    cookies = []
    for cookie in session.cookies:
        cookies.append(
            {
                "name": cookie.name,
                "value": cookie.value,
                "domain": cookie.domain or host,
                "path": cookie.path or "/",
                "httpOnly": bool(cookie.has_nonstandard_attr("HttpOnly")),
                "secure": bool(cookie.secure),
            }
        )
    return cookies


def redaction_css(scene: Dict[str, Any], defaults: Dict[str, Any], policy: str) -> str:
    always = list(resolve(scene, defaults, "redact_always", []) or [])
    extra = list(scene.get("redact_extra", []) or [])
    if policy == "pass":
        return ""
    selectors = always + extra
    if policy == "blur":
        selectors += list(resolve(scene, defaults, "redact", []) or [])
    selectors = [s for s in selectors if isinstance(s, str) and s.strip()]
    if not selectors:
        return ""
    joined = ",\n".join(selectors)
    return (
        f"{joined} {{\n"
        "  filter: blur(24px) grayscale(0.92) !important;\n"
        "  background-image: none !important;\n"
        "}\n"
    )


def _run_steps(page: Any, steps: Sequence[Dict[str, Any]], timeout_ms: int) -> None:
    for step in steps:
        if "click" in step:
            page.locator(step["click"]).first.click(timeout=timeout_ms)
        elif "wait_for" in step:
            page.locator(step["wait_for"]).first.wait_for(state="visible", timeout=timeout_ms)
        elif "wait_ms" in step:
            page.wait_for_timeout(step["wait_ms"])
        elif "hide" in step:
            page.eval_on_selector_all(
                step["hide"], "els => els.forEach(el => { el.style.visibility = 'hidden'; })"
            )
        elif "scroll_to" in step:
            page.locator(step["scroll_to"]).first.scroll_into_view_if_needed(timeout=timeout_ms)
        elif "fill" in step:
            page.locator(step["fill"]["selector"]).first.fill(step["fill"]["value"], timeout=timeout_ms)
        elif "set_text" in step:
            page.eval_on_selector_all(
                step["set_text"]["selector"],
                "(els, value) => els.forEach(el => { el.textContent = value; })",
                step["set_text"]["value"],
            )
        elif "press" in step:
            page.locator(step["press"]["selector"]).first.press(step["press"]["key"], timeout=timeout_ms)


def compare_png(existing: Path, candidate: Path) -> Tuple[float, str]:
    """Return (fraction of changed pixels, human summary).

    Font hinting and antialiasing move a handful of pixels between otherwise
    identical renders, so callers apply a tolerance instead of demanding an exact
    match. Without Pillow there is no pixel view, so any byte difference counts
    as a full change.
    """
    if existing.read_bytes() == candidate.read_bytes():
        return 0.0, "identical"
    try:
        from PIL import Image, ImageChops
    except ImportError:
        return 1.0, "bytes differ (install pillow for a pixel diff)"
    with Image.open(existing) as before, Image.open(candidate) as after:
        if before.size != after.size:
            return 1.0, f"size {before.size} -> {after.size}"
        diff = ImageChops.difference(before.convert("RGB"), after.convert("RGB"))
        bbox = diff.getbbox()
        if bbox is None:
            return 0.0, "pixel-identical"
        histogram = diff.convert("L").histogram()
        total = sum(histogram)
        changed = total - histogram[0]
        fraction = changed / total if total else 0.0
        return fraction, f"{fraction:.2%} of pixels changed, bbox {bbox}"


def capture(manifest: Dict[str, Any], scene_ids: Sequence[str], base_url: str, out_dir: Optional[Path],
            check: bool, allow_real_media: bool, verify_tls: bool, headed: bool, timeout_ms: int,
            check_tolerance: float = 0.002) -> int:
    defaults = scene_defaults(manifest)
    scenes = enabled_scenes(manifest)
    if scene_ids:
        wanted = set(scene_ids)
        unknown = wanted - {s["id"] for s in manifest["scenes"]}
        if unknown:
            print(f"ui shots: unknown scene(s): {', '.join(sorted(unknown))}", file=sys.stderr)
            return 2
        scenes = [s for s in manifest["scenes"] if s["id"] in wanted]
    if not scenes:
        print("ui shots: nothing to capture")
        return 0

    for scene in scenes:
        if resolve(scene, defaults, "media_policy", "placeholder") == "pass" and not allow_real_media:
            print(
                f"ui shots: scene '{scene['id']}' asks for media_policy=pass; "
                "re-run with --allow-real-media only when the source streams are rights-cleared "
                "and contain no personal data",
                file=sys.stderr,
            )
            return 2

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print(
            "ui shots: playwright is not installed.\n"
            "  uv pip install --python .venv/bin/python -r requirements-docs.txt\n"
            "  .venv/bin/python -m playwright install chromium",
            file=sys.stderr,
        )
        return 2

    app_version = ""
    version_file = REPO_ROOT / "VERSION"
    if version_file.is_file():
        app_version = version_file.read_text(encoding="utf-8").strip()

    cookie_cache: Dict[str, List[Dict[str, Any]]] = {}
    failures: List[str] = []
    differences: List[str] = []
    written: List[str] = []

    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=not headed)
        try:
            for scene in scenes:
                scene_id = scene["id"]
                role = scene.get("auth", "none")
                policy = resolve(scene, defaults, "media_policy", "placeholder")
                viewport = resolve(scene, defaults, "viewport", {"width": 1600, "height": 1000})

                if role != "none" and role not in cookie_cache:
                    creds = credentials_for(role)
                    if creds is None:
                        failures.append(
                            f"{scene_id}: no credentials for role '{role}' "
                            f"(set EVA_SHOTS_{role.upper()}_USER / _PASSWORD)"
                        )
                        continue
                    try:
                        cookie_cache[role] = login_cookies(base_url, creds[0], creds[1], verify_tls)
                    except Exception as exc:  # noqa: BLE001 - report, keep going with other scenes
                        failures.append(f"{scene_id}: login as '{role}' failed: {exc}")
                        continue

                context = browser.new_context(
                    viewport={"width": int(viewport["width"]), "height": int(viewport["height"])},
                    device_scale_factor=float(resolve(scene, defaults, "device_scale_factor", 1)),
                    color_scheme=resolve(scene, defaults, "color_scheme", "dark"),
                    locale=resolve(scene, defaults, "locale", "en-US"),
                    ignore_https_errors=not verify_tls,
                    reduced_motion="reduce",
                )
                try:
                    if role != "none":
                        context.add_cookies(cookie_cache[role])

                    seeds = resolve(scene, defaults, "local_storage", {}) or {}
                    if seeds:
                        # add_init_script takes no arguments, so the values are inlined as JSON.
                        context.add_init_script(
                            "for (const [k, v] of " + json.dumps(list(seeds.items())) + ") {"
                            " try { window.localStorage.setItem(k, v); } catch (e) {} }"
                        )

                    if policy == "placeholder":
                        def serve_placeholder(route: Any) -> None:
                            route.fulfill(status=200, content_type="image/svg+xml", body=PLACEHOLDER_SVG)

                        for pattern in EVIDENCE_URL_PATTERNS:
                            context.route(pattern, serve_placeholder)

                    page = context.new_page()
                    page.goto(base_url.rstrip("/") + scene["path"], wait_until="domcontentloaded",
                              timeout=timeout_ms)
                    _run_steps(page, scene.get("steps", []), timeout_ms)

                    page.add_style_tag(content=DETERMINISM_CSS)
                    css = redaction_css(scene, defaults, policy)
                    if css:
                        page.add_style_tag(content=css)
                    page.wait_for_timeout(int(resolve(scene, defaults, "settle_ms", 1500)))

                    output_rel = scene["output"]
                    target = (out_dir / Path(output_rel).name) if out_dir else (REPO_ROOT / output_rel)
                    target.parent.mkdir(parents=True, exist_ok=True)

                    if check:
                        import tempfile

                        with tempfile.TemporaryDirectory() as tmp:
                            candidate = Path(tmp) / "candidate.png"
                            _shoot(page, scene, candidate, timeout_ms)
                            if not target.is_file():
                                differences.append(f"{scene_id}: no committed screenshot at {output_rel}")
                            else:
                                fraction, summary = compare_png(target, candidate)
                                if fraction > check_tolerance:
                                    differences.append(f"{scene_id}: {summary}")
                                elif fraction > 0:
                                    print(f"ui shots: {scene_id} within tolerance ({summary})")
                        continue

                    _shoot(page, scene, target, timeout_ms)
                    written.append(scene_id)
                    if not out_dir:
                        meta = {
                            "scene": scene_id,
                            "tool": TOOL_ID,
                            "captured_at_utc": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
                            "app_version": app_version,
                            "ui": scene.get("ui"),
                            "auth_role": role,
                            "media_policy": policy,
                            "viewport": viewport,
                            "source_fingerprint": source_fingerprint(scene.get("ui", "legacy")),
                        }
                        sidecar_path(output_rel).write_text(
                            json.dumps(meta, indent=2, sort_keys=True) + "\n", encoding="utf-8"
                        )
                except Exception as exc:  # noqa: BLE001 - one broken scene must not abort the run
                    failures.append(f"{scene_id}: {type(exc).__name__}: {exc}")
                finally:
                    context.close()
        finally:
            browser.close()

    for scene_id in written:
        print(f"ui shots: captured {scene_id}")
    for message in differences:
        print(f"ui shots STALE: {message}")
    for message in failures:
        print(f"ui shots FAILED: {message}", file=sys.stderr)

    if failures:
        return 1
    if differences:
        print("ui shots: committed screenshots are out of date; re-run without --check")
        return 1
    print("ui shots: OK")
    return 0


def _shoot(page: Any, scene: Dict[str, Any], target: Path, timeout_ms: int) -> None:
    clip = scene.get("clip")
    if clip:
        page.locator(clip).first.screenshot(path=str(target), timeout=timeout_ms)
    else:
        page.screenshot(path=str(target))


# --------------------------------------------------------------------------
# cli
# --------------------------------------------------------------------------


def cmd_list(manifest: Dict[str, Any]) -> int:
    defaults = scene_defaults(manifest)
    for scene in manifest["scenes"]:
        state = "" if scene.get("enabled", True) else "  [disabled]"
        captured = "captured" if (REPO_ROOT / scene.get("output", "")).is_file() else "pending"
        print(
            f"{scene.get('id'):<32} {scene.get('ui'):<7} auth={scene.get('auth', 'none'):<9} "
            f"media={resolve(scene, defaults, 'media_policy', 'placeholder'):<12} {captured}{state}"
        )
    return 0


def cmd_snippet(manifest: Dict[str, Any], scene_id: str, doc: Optional[str]) -> int:
    """Print the markdown to paste into a guide, with the path relative to that guide."""
    scenes = {scene["id"]: scene for scene in manifest["scenes"] if isinstance(scene.get("id"), str)}
    scene = scenes.get(scene_id)
    if scene is None:
        print(f"ui shots: unknown scene '{scene_id}'", file=sys.stderr)
        return 2
    output = scene["output"]
    docs = [doc] if doc else (scene.get("used_by") or [])
    if not docs:
        print(f"![{scene['caption']}]({output})")
        return 0
    for target in docs:
        base = (REPO_ROOT / target).parent
        relative = os.path.relpath(REPO_ROOT / output, base)
        print(f"# {target}")
        print(f"![{scene['caption']}]({relative})")
    return 0


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH)
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser("validate", help="check the manifest and committed assets (no browser)")
    validate_parser.add_argument("--strict", action="store_true", help="treat warnings as failures")

    subparsers.add_parser("list", help="list scenes and their capture state")

    snippet_parser = subparsers.add_parser("snippet", help="print the markdown embed for a scene")
    snippet_parser.add_argument("scene")
    snippet_parser.add_argument("--doc", default=None, help="target doc (default: the scene's used_by list)")

    capture_parser = subparsers.add_parser("capture", help="drive a running EVA and write screenshots")
    capture_parser.add_argument("--scene", action="append", default=[], help="scene id (repeatable)")
    capture_parser.add_argument(
        "--base-url",
        default=os.getenv("EVA_SHOTS_BASE_URL", "http://127.0.0.1:5000"),
        help="running EVA instance (default: $EVA_SHOTS_BASE_URL or http://127.0.0.1:5000)",
    )
    capture_parser.add_argument("--out-dir", type=Path, default=None,
                                help="write elsewhere than docs/ui/assets (smoke runs; skips sidecars)")
    capture_parser.add_argument("--check", action="store_true",
                                help="compare against committed screenshots instead of writing")
    capture_parser.add_argument("--check-tolerance", type=float, default=0.002,
                                help="fraction of pixels that may differ before --check calls a shot stale")
    capture_parser.add_argument("--allow-real-media", action="store_true",
                                help="permit media_policy=pass scenes (rights-cleared, non-personal streams only)")
    capture_parser.add_argument("--verify-tls", action="store_true", help="verify TLS (off for dev self-signed certs)")
    capture_parser.add_argument("--headed", action="store_true", help="show the browser window")
    capture_parser.add_argument("--timeout-ms", type=int, default=20000)

    args = parser.parse_args(argv)

    try:
        manifest = load_manifest(args.manifest)
    except ManifestError as exc:
        print(f"ui shots ERROR: {exc}", file=sys.stderr)
        return 1

    if args.command == "validate":
        return validate(manifest, strict=args.strict)
    if args.command == "list":
        return cmd_list(manifest)
    if args.command == "snippet":
        return cmd_snippet(manifest, args.scene, args.doc)
    if args.command == "capture":
        rc = validate(manifest, strict=False)
        if rc != 0:
            print("ui shots: fix the manifest before capturing", file=sys.stderr)
            return rc
        return capture(
            manifest,
            scene_ids=args.scene,
            base_url=args.base_url,
            out_dir=args.out_dir,
            check=args.check,
            allow_real_media=args.allow_real_media,
            verify_tls=args.verify_tls,
            headed=args.headed,
            timeout_ms=args.timeout_ms,
            check_tolerance=args.check_tolerance,
        )
    parser.error(f"unknown command {args.command}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
